### ISSUE TITLE
有Fleet使用DGC的示例吗

### ISSUE THREAD

**Issue by listenlink** [PaddlePaddle/Fleet#55]
Fleet的collective源码主要实现了dgc算法，请问有用dgc算法进行分布式训练的示例吗

**Comment by guru4elephant** [comment]
@listenlink 未来会添加

**Comment by listenlink** [comment]
@guru4elephant 多谢回复：） 请教下dgc算法目前内部是否有精度问题？之前在paddlepaddle/models里示范用例dgc算法出现了Loss NAN的问题，尚未得到解答https://github.com/PaddlePaddle/models/issues/3145

**Comment by wangxicoding** [comment]
@listenlink 目前已在fleet下添加dgc的示例。
dgc数字识别的简单示例： https://github.com/PaddlePaddle/Fleet/tree/develop/examples/dgc_example
resnet下也添加了DGC相应代码： https://github.com/PaddlePaddle/Fleet/tree/develop/benchmark/collective/resnet
之前DGC确实存在有一些流程上的问题造成了一定的精度损失，不过你遇到的loss NAN可能是另一个bug导致的，现在这两问题均已修复。
最新DGC需要paddle1.6.2版本(可能需要本月中旬发布），目前可以使用最新的develop分支版本进行测试验证https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/install/Tables.html#whl-dev
若还有其它问题，谢谢你及时反馈。

**Comment by xbinglzh** [comment]
https://github.com/PaddlePaddle/Fleet/tree/develop/examples/dgc_example
https://github.com/PaddlePaddle/Fleet/tree/develop/benchmark/collective/resnet
这些 examples 都去哪里了  完全打不开了
https://github.com/PaddlePaddle/FleetX/tree/develop/examples 文档也不更新下

**Comment by wangxicoding** [comment]
> https://github.com/PaddlePaddle/Fleet/tree/develop/examples/dgc_example https://github.com/PaddlePaddle/Fleet/tree/develop/benchmark/collective/resnet 这些 examples 都去哪里了 完全打不开了 https://github.com/PaddlePaddle/FleetX/tree/develop/examples 文档也不更新下

@xbinglzh 看了下develop代码都给重构了，估计相关功能代码都还没加上去。可以用用以前的分支，试试这个链接，https://github.com/PaddlePaddle/PaddleFleetX/blob/old_develop/examples/resnet/train_fleet_static_dgc.py
有啥问题或者需要demo应该可以问 @wuhuachaocoding ，他负责接手这部分功能
