### ISSUE TITLE
*** SIGTERM (@0x38400000db2) received by PID 5342 (TID 0x7efe568a6700) from PID 3506; stack trace: ***

### ISSUE THREAD

**Issue by bit-pku-zdf** [PaddlePaddle/Fleet#74]
在孔明集群中运行collective demo，出现如下错误

WARNING:root:set nccl_comm_num=1 since you only have 1 node. server not ready, wait 3 sec to retry... not ready endpoints:['127.0.0.1:6171', '127.0.0.1:6172', '127.0.0.1:6173', '127.0.0.1:6174', '127.0.0.1:6175', '127.0.0.1:6176', '127.0.0.1:6177'] server not ready, wait 3 sec to retry... not ready endpoints:['127.0.0.1:6171', '127.0.0.1:6172', '127.0.0.1:6173', '127.0.0.1:6174', '127.0.0.1:6175', '127.0.0.1:6176', '127.0.0.1:6177'] server not ready, wait 3 sec to retry... not ready endpoints:['127.0.0.1:6171', '127.0.0.1:6172', '127.0.0.1:6173', '127.0.0.1:6174', '127.0.0.1:6175', '127.0.0.1:6176', '127.0.0.1:6177'] W1005 11:17:27.760031 5342 init.cc:212] *** Aborted at 1570245447 (unix time) try "date -d @1570245447" if you are using GNU date *** W1005 11:17:27.761384 5342 init.cc:212] PC: @ 0x0 (unknown) W1005 11:17:27.761484 5342 init.cc:212] *** SIGTERM (@0x38400000db2) received by PID 5342 (TID 0x7efe568a6700) from PID 3506; stack trace: *** W1005 11:17:27.762459 5342 init.cc:212] @ 0x7efe5647d160 (unknown) W1005 11:17:27.763466 5342 init.cc:212] @ 0x7efe55a95ed3 __GI_select W1005 11:17:27.764262 5342 init.cc:212] @ 0x7efe4aa9b2ad time_sleep W1005 11:17:27.764425 5342 init.cc:212] @ 0x4b8934 PyEval_EvalFrameEx W1005 11:17:27.764565 5342 init.cc:212] @ 0x4b88af PyEval_EvalFrameEx W1005 11:17:27.764710 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.764847 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.764991 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.765123 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.765264 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.765395 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.765534 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.765666 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.765805 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.765940 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.766070 5342 init.cc:212] @ 0x4b88af PyEval_EvalFrameEx W1005 11:17:27.766199 5342 init.cc:212] @ 0x4b88af PyEval_EvalFrameEx W1005 11:17:27.766336 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.766465 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.766604 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.766733 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.766877 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.767011 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.767155 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.767288 5342 init.cc:212] @ 0x4b83b7 PyEval_EvalFrameEx W1005 11:17:27.767426 5342 init.cc:212] @ 0x4ba7c8 PyEval_EvalCodeEx W1005 11:17:27.767554 5342 init.cc:212] @ 0x4ba8f2 PyEval_EvalCode W1005 11:17:27.767681 5342 init.cc:212] @ 0x4e6e9d PyRun_FileExFlags W1005 11:17:27.767832 5342 init.cc:212] @ 0x4e8721 PyRun_SimpleFileExFlags W1005 11:17:27.767956 5342 init.cc:212] @ 0x415bbd Py_Main W1005 11:17:27.768987 5342 init.cc:212] @ 0x7efe559d7bd5 __libc_start_main W1005 11:17:27.769170 5342 init.cc:212] @ 0x414d51 (unknown)

job 地址
http://yq01-sys-hic-p40-0189.yq01.baidu.com:8388/v1/slurmjobs/137316/workspace
麻烦哪位大神可以帮忙解决，万分感谢

**Comment by sandyhouse** [comment]
请查看具体trainer的日志，如mylog/workerlog.2，显示GPU OOM，请设置合适的batch size等参数，并确保没有别的进程占用该卡（可以使用nvidia-smi查看GPU占用情况）。另外，可以通过export FLAGS_eager_delete_tensor_gb=0.0启动gc功能。

**Comment by sandyhouse** [comment]
Closing this issue. Reopen it if you have any further question.
